export const signupTypes = {
  SIGN_UP_LOADING: "SIGN_UP_LOADING",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
};

export const signInTypes = {
  SIGN_IN_LOADING: "SIGN_IN_LOADING",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_ERROR: "SIGN_IN_ERROR",
};
