export const getBlog = {
  GET_BLOG_SNAPSHOTS_LOADING: "GET_BLOG_SNAPSHOTS_LOADING",
  GET_BLOG_SNAPSHOTS_SUCCESS: "GET_BLOG_SNAPSHOTS_SUCCESS",
  GET_BLOG_SNAPSHOTS_ERROR: "GET_BLOG_SNAPSHOTS_ERROR",
};
