export const getBlogTypes = {
  GET_BLOG_SNAPSHOTS_LOADING: "GET_BLOG_SNAPSHOTS_LOADING",
  GET_BLOG_SNAPSHOTS_SUCCESS: "GET_BLOG_SNAPSHOTS_SUCCESS",
  GET_BLOG_SNAPSHOTS_ERROR: "GET_BLOG_SNAPSHOTS_ERROR",
};

export const postBlogTypes = {
  POST_BLOG_SNAPSHOTS_LOADING: "POST_BLOG_SNAPSHOTS_LOADING",
  POST_BLOG_SNAPSHOTS_SUCCESS: "POST_BLOG_SNAPSHOTS_SUCCESS",
  POST_BLOG_SNAPSHOTS_ERROR: "POST_BLOG_SNAPSHOTS_ERROR",
  POST_BLOG_SNAPSHOT_RESET: "POST_BLOG_SNAPSHOT_RESET",
};

export const getSpecificBlogTypes = {
  GET_SPECIFIC_BLOG_LOADING: "GET_SPECIFIC_BLOG_LOADING",
  GET_SPECIFIC_BLOG_SUCCESS: "GET_SPECIFIC_BLOG_SUCCESS",
  GET_SPECIFIC_BLOG_ERROR: "GET_SPECIFIC_BLOG_ERROR",
};
