export const GET_BLOG_SNAPSHOTS_LOADING = "GET_BLOG_SNAPSHOTS_LOADING";
export const GET_BLOG_SNAPSHOTS_SUCCESS = "GET_BLOG_SNAPSHOTS_SUCCESS";
export const GET_BLOG_SNAPSHOTS_ERROR = "GET_BLOG_SNAPSHOTS_ERROR";
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
