export const categoryAddForHomeScreenTypes = {
  HOMESCREEN_CATEGORY_ADD_LOADING: "HOMESCREEN_CATEGORY_ADD_LOADING",
  HOMESCREEN_CATEGORY_ADD_SUCCESS: "HOMESCREEN_CATEGORY_ADD_SUCCESS",
  HOMESCREEN_CATEGORY_ADD_ERROR: "HOMESCREEN_CATEGORY_ADD_ERROR",
};

export const categoryViewForHomeScreenTypes = {
  HOMESCREEN_CATEGORY_VIEW_LOADING: "HOMESCREEN_CATEGORY_VIEW_LOADING",
  HOMESCREEN_CATEGORY_VIEW_SUCCESS: "HOMESCREEN_CATEGORY_VIEW_SUCCESS",
  HOMESCREEN_CATEGORY_VIEW_ERROR: "HOMESCREEN_CATEGORY_VIEW_ERROR",
};
