export const subHeaderViewTypes = {
  SUBHEADER_VIEW_LOADING: "SUBHEADER_VIEW_LOADING",
  SUBHEADER_VIEW_SUCCESS: "SUBHEADER_VIEW_SUCCESS",
  SUBHEADER_VIEW_ERROR: "SUBHEADER_VIEW_ERROR",
};

export const subHeaderAddTypes = {
  SUBHEADER_ADD_LOADING: "SUBHEADER_ADD_LOADING",
  SUBHEADER_ADD_SUCCESS: "SUBHEADER_ADD_SUCCESS",
  SUBHEADER_ADD_ERROR: "SUBHEADER_ADD_ERROR",
};
